condense_wildcard_suffixes = true
empty_item_single_line = false
hard_tabs = true
imports_layout = 'HorizontalVertical'
match_block_trailing_comma = true
imports_granularity = 'Crate'
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = 'StdExternalCrate'
report_fixme = 'Always'
report_todo = 'Always'
use_field_init_shorthand = true
