hard_tabs = true
overflow_delimited_expr = true
empty_item_single_line = false

reorder_impl_items = true
use_field_init_shorthand = true
match_block_trailing_comma = true

imports_granularity = 'Crate'
group_imports = 'StdExternalCrate'
imports_layout = 'HorizontalVertical'
